### PR TITLE
Add ability to unset an array. Closes #45

### LINKED ISSUE #45: Feature request: Pass array to .unset()
It would be handy to be able to parse an array of keys to unset when calling unset().
this.model.unset(["prop1", "prop2"]);

Also, the docs on http://ampersandjs.com/docs#ampersand-state-set when using "unset" as option do not make clear what it actually does.

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by kamilogorek** [comment]
Looks fine! @pgilad thanks for all your contributions so far, great work! :)

**Comment by pgilad** [comment]
No problem... I want to see Ampersand succeeding :trophy:

**Comment by wraithgar** [comment]
+1.  Array.isArray is IE9+ for those wondering.

**Comment by pgilad** [comment]
Isn't Object.defineProperty IE9+ as well, so basically that is the par line?

I can rebase this with `_.isArray` if needed

**Comment by wraithgar** [comment]
Nope! IE9 is our base target, was just confirming that this doesn't change anything in re our requirements.  Thanks for the mountain of PRs you sent in the last few days!

**Comment by pgilad** [comment]
No problem :smile:

**Comment by wraithgar** [comment]
published as `v4.5.0`

**Pull request merged**
