### PR TITLE
Bump lodash to v4

### PR DESCRIPTION
**Pull request by samhashemi**

### CODE REVIEW

**Comment by samhashemi** [comment]
@wraithgar @latentflip @cdaringe @pgilad 

I've taken a first swing at updating AmpersandJS to lodash v4. `Model`, `View`, and `Events` were updated to v4 in previous pull requests, so I've made 10 additional PRs to update the rest of the project.

A few of the packages depend on other ampersand packages that need to be updated, which I've noted below.

https://github.com/AmpersandJS/ampersand-state/pull/241
https://github.com/AmpersandJS/ampersand-app/pull/8
https://github.com/AmpersandJS/ampersand-router/pull/52
https://github.com/AmpersandJS/ampersand-class-extend/pull/9
https://github.com/AmpersandJS/ampersand-sync/pull/76
https://github.com/AmpersandJS/ampersand-collection-lodash-mixin/pull/11

Depends on `ampersand-sync`, updated above:
https://github.com/AmpersandJS/ampersand-collection-rest-mixin/pull/41

Depends on `ampersand-class-extend`, updated above:
https://github.com/AmpersandJS/ampersand-collection/pull/80
https://github.com/AmpersandJS/ampersand-collection-view/pull/44
https://github.com/AmpersandJS/ampersand-filtered-subcollection/pull/31

If there's anything I can do to help merge these quickly, let me know. They should all be fairly straightforward.

**Comment by pgilad** [comment]
Verified that all zuul tests run via https://github.com/AmpersandJS/ampersand-state/pull/242

**Comment by samhashemi** [comment]
@pgilad thanks for looking through these. is there another person on the ampersand team who can give a second thumbs up?

**Comment by pgilad** [comment]
ping @AmpersandJS/core-team

**Comment by cdaringe** [comment]
+1

**Comment by lukekarrys** [comment]
+1

**Comment by samhashemi** [comment]
@cdaringe @lukekarrys thanks. could one of you look through the related commits above? these changes are much more impactful if they are done across the ampersand project -- it makes it possible to transition entirely to lodash v4 instead of requiring two different versions. This can be a huge difference in number of bytes.

**Comment by samhashemi** [comment]
@cdaringe @lukekarrys @pgilad @AmpersandJS/core-team i'm getting the sinking feeling this project isn't being actively maintained. 

is there a clear person i should work with to get these merged and pushed to NPM? is the best option forking all the libraries?

**Comment by cdaringe** [comment]
hey @samhashemi, sorry to give that impression :/ my experience has told me that we've had the implicit practice of letting the package maintainer take charge of merge/publish.  im not sure who does -state, but i'm sure it was just a case of "too-busy."  thanks for following up.  we'll get it taken care of.

**Comment by cdaringe** [comment]
@pgilad let me know if you want me to publish

**Comment by samhashemi** [comment]
@cdaringe thanks! is there a list of who the maintainer is for each ampersand project? i'd like to get the 10 PRs above merged in parallel.

**Comment by latentflip** [comment]
@cdaringe I think at one point I was, but I'm taking a back seat from things right now, so if you have publish bits go ahead and do what you think's right :)

**Comment by cdaringe** [comment]
@samhashemi, it should be listed on the packages (like [here](https://github.com/AmpersandJS/ampersand-view/#ampersand-view))
@latentflip i'll add ya as such ^^ for this package (even in presence of the backsaet comment for now, just to remove ambiguity).  if we need to swap out or elect a new lead for this pkg, let's get a new thread goin!

i'll publish this bad boy :)

**Comment by cdaringe** [comment]
`5.0.2` is up!

**Comment by latentflip** [comment]
Okay, I definitely shouldn't be listed as I'll be of no use, so I opened this: https://github.com/AmpersandJS/ampersand-state/issues/243

**Comment by pgilad** [comment]
Publish, and publish all related repositories as well... I didn't have publish rights to all of them so decided not to get stuck in the middle of the upgrade

**Pull request merged**
