### PR TITLE
Remove need for lodash/bind; Optimize

### PR DESCRIPTION
**Pull request by dhritzkiv**
- Update ampersand-events (which incorporates lodash updates)
- Update lodash to v4, using single module vs. invidual modules. Correct argument pattern for `lodash.forOwn` (`this` is no longer a third argument?)
- Remove `lodash.bind`; use native `.bind`. Previously required for phantomjs (see next point)
- Update phantomjs to v2, which includes `.bind`. Installs using recommended `phantomjs-prebuilt`
- Update coveralls, tape, zuul
- Reuse similar code (at L105)

### CODE REVIEW

**Comment by pgilad** [comment]
Great job! BTW, all the lodash includes are case-sensitive (depending on OS/FS but ubuntu is), meaning
`var isString = require('lodash/isstring');` will fail in ubuntu but pass in osx.
You need to reference the exact file:
`var isString = require('lodash/isString');`

**Comment by dhritzkiv** [comment]
Good catch. I totally forgot about that behaviour.

**Comment by wraithgar** [comment]
You'll likely need to rebase this PR against master, there was a bugfix PR from last week I just merged.

**Comment by wraithgar** [comment]
This looks good to me, Let's not merge this until I've published a patch release from pr #235 so we don't unnecessarily couple this lodash update with that bugfix

**Comment by dhritzkiv** [comment]
I saw that ampersand-view was updated recently to v10 to include lodash@v4 as well as ampersand-state@v5. However, ampersand-state@v5 still uses older lodash versions (addressed via this PR). When this gets a merge + release, ampersand-view will need its ampersand-state dependency updated, which will mean a new major version.

**Comment by cdaringe** [comment]
are we sure that it would be a major?  no breaking changes would occur. dep swaps would occur, but no functionality or API change would be expected.  IMHO, it's a patch, unless there's something im missing from the &-events bump.

**Comment by dhritzkiv** [comment]
That's a fair point.

I suppose my thinking was: `ampersand-state` is a critical part of `ampersand-view`, and any major version bumps of `-state` (other ampersand modules received a major update for the lodash upgrade) would require a major version bump of `-view`. But behaviourally, this PR shouldn't break anything.

**Comment by dhritzkiv** [comment]
Any update on this PR?

**Comment by cdaringe** [comment]
looks good to me!  loving all the 🔴 lines. :)  @wraithgar's PR is merged, so hopefully he's cool with proceeding now.

**Comment by dhritzkiv** [comment]
I merged in master, so the main changes are now:

- removing the requirement for lodash's bind method and using native bind
    - accomplished by using an updated version of phantom that includes support for `Function.prototype.bind`
- DRYer functions that simplify setting the value from serialised children or collections

**Comment by dhritzkiv** [comment]
Bump. The tests are actually passing (see the test details) and the coverage decrease is minimal. Seems this got lots of thumbs up previously. Good to merge?

**Comment by wraithgar** [comment]
Yes, great!

**Pull request merged**
