### PR TITLE
Remove unused vars and cleanup code

### PR DESCRIPTION
**Pull request by pgilad**
- Closes #61

### CODE REVIEW

**Comment by latentflip** [comment]
:+1:

**Comment by wraithgar** [comment]
not sure why that exception is being changed but I also don't really care as long as the message is still legible (it is). All other changes are to tests only. :shipit:

**Comment by pgilad** [comment]
Message being changed to maintain consistency with how we present erroneous keys (with tildes).

**Comment by kamilogorek** [comment]
:+1:

**Pull request merged**
