### PR TITLE
bubble changes from collections

### LINKED ISSUE #66: Derived properties don't listen to change events from collections
Simplified example:

``` javascript
var Model = require('ampersand-model');
var Collection = require('ampersand-collection');

var Room = Model.extend({
  props: {
    size: ['number', true, 10],
  },
});

var Rooms = Collection.extend({
  model: Room,
});

var House = Model.extend({
  collections: {
    rooms: Rooms,
  },

  derived: {
    totalArea: {
      deps: ['rooms'],
      fn: function() {
        return this.rooms.reduce(function(a, b) {
          return a + b.size;
        }, 0);
      }
    }
  },
});

var house = new House({
  rooms: [{size: 12}]
});

console.log(house.totalArea); // => 12
house.rooms.at(0).size = 15;
console.log(house.totalArea); // => 12
```

Seems like this should work?

### PR DESCRIPTION
**Pull request by lukekarrys**
Fixes #66

### CODE REVIEW

**Comment by cwarden** [comment]
There seem to be two issues conflated here, the propagation of events from child/collection objects to the parent, and the binding to these events to update derived properties.  I ran into the former with child properties, and it seems worth fixing, independent of the problem with derived properties.

Here's an example that fails which is unrelated to derived properties: #123

**Comment by samhashemi** [comment]
@lukekarrys any update on this?

**Comment by lukekarrys** [comment]
Unfortunately, I don't think this is going to land in it's current form. I used something similar to this in a project and ended up removing a lot of it as it was causing perf problems for ~300 count collections. Not to say I don't think this would be useful, but enabling it wholesale for state and collection I think would open people up to unintentionally create hard-to-solve perf problems in their apps.

**Comment by jvduf** [comment]
I've made a custom implementation myself which uses a flag to enable
bubbling using namespaced events. Is that something we should consider to
implement. This should be very well thought through (i have not done this
yet).


*Jeroen van Duffelen*
+31 6 2854 1275
@jvduf

**Comment by lukekarrys** [comment]
I'm going to close this since this isn't going to be merged in its current form.

Also linking to https://github.com/AmpersandJS/ampersand-collection/issues/48 which might be a better place for this discussion.

**Pull request closed without merging**
