### PR TITLE
Add safeSet for children & collections

### PR DESCRIPTION
**Pull request by pgilad**
- Closes https://github.com/AmpersandJS/ampersand-view/pull/128
- Closes https://github.com/AmpersandJS/ampersand-view/issues/96

### CODE REVIEW

**Comment by kamilogorek** [comment]
Are we sure that we want to throw when it happens instead of just inform dev?

**Comment by pgilad** [comment]
My thoughts are that if you're doing something wrong (which will cause errors down the line), throw loudly. I'd rather have that than a `console.log`.

**Comment by cdaringe** [comment]
+1

**Comment by lukekarrys** [comment]
+1

**Pull request merged**
