### PR TITLE
Coerce numbers into booleans

### PR DESCRIPTION
**Pull request by dhritzkiv**
In many cases, it's preferable to use integers to indicate `true` or `false` values, and in some of those cases, it's not possible to cast those numerical values to a Boolean. A common use case is using bitwise operators, which return an integer, to determine truthiness. Simple example: `myBool ^= true` as a way to affect/toggle a value inline (without relying on the more functional `model.toggle("myBool")`)

I propose a setter that casts the incoming number value into a Boolean.

I understand that this may be accomplished through a custom data type, but I feel that this is something that should be done automatically.

### CODE REVIEW

**Comment by kamilogorek** [comment]
Sounds reasonable to me. Tests are in place, code is fine. +1 from me.

**Comment by pgilad** [comment]
+1. `isNumber` vs `isFinite` though?

**Comment by dhritzkiv** [comment]
Good catch. Didn't realize lodash had an `isFinite` method that was equivalent to ES6's `Number.isFinite`

**Comment by pgilad** [comment]
Are we good to merge this?

**Comment by latentflip** [comment]
Hey, sorry for the slow update on this.

My thinking is that while I can see this is useful in the case where you want to numbers as booleans, it's not totally obvious to me it should go in core. It would make more sense to me as a mixin that you could use to modify/add a datatype to your app that supported it instead.

The docs on custom dataTypes aren't great, but here's an example of one: https://github.com/legastero/ampersand-jid-datatype-mixin

You just define the extra datatypes you want in the dataTypes section of your state extend().

**Comment by dhritzkiv** [comment]
@latentflip That's fair. This was mainly born from the need to perform bitwise assignment operations on the boolean values (but also had the obvious side-effect of being able to use numbers –`0` & `1`– as booleans).

I suppose that is a specific use-case and warrants a custom data-type.

**Pull request closed without merging**
