### PR TITLE
Serialize state props on toJSON

### LINKED ISSUE #197: toJSON does not serialize state props
Well, it's in the title. Collections and children are serialized, but pure props of type `state` aren't

### PR DESCRIPTION
**Pull request by pgilad**
- Adds a failing test & fix #197

### CODE REVIEW

**Comment by cdaringe** [comment]
yup, this makes sense.  i think it's good as is, but _perhaps_ we should simply sniff for a serialize fn at all, and if it exists call it.  that way it would work with custom types too, if they define `serialize()`?  It may only be ~0.01% of use cases, but hey, just thinkin' out loud.

`if (raw && val && val.serialize && typeof val.serialize === 'function') val = val.serialize();`

+1 either way

**Comment by pgilad** [comment]
Yeah I definitely like leaving off serialize to customTypes, that might be a cruel breaking change though for anyone actually using that function in their custom dataType.

**Comment by kamilogorek** [comment]
Those 4 immediate checks though... :D :+1:

**Comment by pgilad** [comment]
Hey @kamilogorek should we run serialize always when it's available or only for `state` types?

**Comment by kamilogorek** [comment]
@pgilad I believe there's not enough overhead to tinker about it and we should just call it when it's there.

**Comment by pgilad** [comment]
@kamilogorek @cdaringe Added support for `customTypes` serialization and added a test for it. Can you guys review?

**Comment by cdaringe** [comment]
+1

**Comment by kamilogorek** [comment]
:+1:

**Comment by pgilad** [comment]
Can any of you guys publish version v4.7.0? https://github.com/AmpersandJS/ampersand-state/commit/c23194ed8ed455804f5601c2971958e34e9c9956

I already pushed tag & version, but don't have publish rights on npm

**Comment by lukekarrys** [comment]
Just added you @pgilad!

**Comment by pgilad** [comment]
:clap:

**Pull request merged**
