### PR TITLE
add documentation for getAttributes

### PR DESCRIPTION
**Pull request by lukekarrys**
Add a section to the documentation explaining `getAttributes`.

Not quite ready for merge since I'm not actually sure what the second parameter (`raw`) should be used for (or if should be left undocumented). Anyone have any insights there?

### CODE REVIEW

**Comment by wraithgar** [comment]
Are we leaving `raw` option undocumented then?

**Comment by lukekarrys** [comment]
I was hoping to get @latentflip's thoughts on that, since I couldn't figure out the use cases for it.

I can see in the code what the option is doing, but I couldn't tell when or why the option should be used. I think it'd be nice to have something like that in the documentation, but without that my vote would be to leave it undocumented.

**Comment by lukekarrys** [comment]
Talked with @latentflip about it and I think it should be documented. Add a second part to the documentation about what `raw` does and that most likely you wouldnt use it when passing data to templates. Also added a date session attribute to the example to visualize the difference when using `raw`.

**Comment by wraithgar** [comment]
+1 very nice

**Comment by lukekarrys** [comment]
Published as `v4.5.3` to get the new docs to npm.

**Pull request merged**
