### PR TITLE
Switch to console.warn for invalid data types

### LINKED ISSUE #214: Runtime crash when using custom types
Hi, I'm experiencing a constant, deterministic crash in my ampersand app since today. The error message I get is:

```
Uncaught TypeError: Invalid data type of `SubCollection` for `widgets` property. Use one of the default types or define your own
```

The only thing I did was clear my `npm` cache and reinstall. All my `ampersand` versions are pinned so I'm sure the error comes from the unpinned deps in `ampersand`'s  module deps (probably `ampersand-model`, although I'm not sure since there are no changelogs available).

My deps versions are:

```
"ampersand-collection": "1.5.0"
"ampersand-collection-underscore-mixin": "1.0.4"
"ampersand-collection-view": "1.4.0"
"ampersand-form-view": "2.4.0"
"ampersand-input-view": "3.1.1"
"ampersand-model": "5.0.3"
"ampersand-react-view-mixin": "0.0.5"
"ampersand-rest-collection": "2.0.4"
"ampersand-router": "1.0.7"
"ampersand-subcollection": "2.0.3"
"ampersand-view": "7.4.2"
"ampersand-view-switcher": "1.1.2"
```

More context: my first error wasn't about `Subcollection` but about using `'*'` instead of `'any'` as a prop type. Once I fixed that, I started seeing the above error.

This breaks my build on prod :(

### PR DESCRIPTION
**Pull request by pgilad**
- Fixes #214

### CODE REVIEW

**Comment by pgilad** [comment]
@latentflip

**Comment by latentflip** [comment]
:+1:

**Comment by STRML** [comment]
Let's get this merged ASAP to fix the breakage. @HenrikJoreteg

**Comment by cdaringe** [comment]
+1

**Pull request merged**
